// ═══════════════════════════════════════════════════════════════
//  CATEGORIES  — icons, colors, keyword lists
// ═══════════════════════════════════════════════════════════════

const CAT = {
  'Income':        { color:'#10b981', icon:'💰', kw:['salary','payroll','direct deposit','paycheck','wages','employer','income','refund','reimbursement','dividend','interest earned','credit received','cashback','tax return','bonus'] },
  'Food & Dining': { color:'#f97316', icon:'🍽️', kw:['restaurant','cafe','coffee','pizza','burger','sushi','mcdonald','starbucks','chipotle','subway','doordash','ubereats','grubhub','dining','bakery','diner','taco','panera','wendys','dunkin','chick-fil','dominos','olive garden','denny','ihop','kfc','popeyes','panda express','five guys','shake shack','waffle house','smoothie king','jamba','tropical smoothie','boba','wing stop','bbq','steakhouse','seafood','bistro','grill','eatery','brunch','sweetgreen','cosi','freshii','moe\'s'] },
  'Groceries':     { color:'#22c55e', icon:'🛒', kw:['grocery','supermarket','whole foods','trader joe','kroger','safeway','publix','albertsons','aldi','sprouts','market basket','stop & shop','food lion','heb','meijer','wegmans','giant','harris teeter','fresh market','smart & final','winn dixie','piggly','price chopper','shoprite','lidl','costco food','sams food','bj\'s food','instacart','fresh direct','peapod','walmart grocery','target grocery','food4less','lucky supermarkets','stater bros','winco'] },
  'Transportation':{ color:'#3b82f6', icon:'🚗', kw:['uber','lyft','gas station','fuel','shell','bp ','chevron','exxon','mobil ','parking','transit','metro','bus fare','taxi','airline','flight','amtrak','greyhound','zipcar','enterprise rent','hertz','avis ','budget car','toll','bart','mta ','wmata','cta ','septa','sunoco','marathon oil','speedway','circle k','wawa gas','autozone','napa auto','oreilly','advance auto','jiffy lube','firestone','goodyear','oil change','valvoline','brake','pep boys','midas','sears auto','national car','alamo rent','dollar rent','thrifty car','fox rent','payless car'] },
  'Shopping':      { color:'#a855f7', icon:'🛍️', kw:['amazon','walmart','target','bestbuy','ebay','etsy','wayfair','ikea','homedepot','lowes','macys','nordstrom','tjmaxx','marshalls','ross ','old navy','gap ','h&m ','zara ','forever 21','express ','j.crew','banana republic','anthropologie','urban outfitters','uniqlo','nike ','adidas ','foot locker','dicks sporting','rei ','patagonia','apple store','microsoft store','office depot','staples','dollar general','dollar tree','five below','bath & body','victoria\'s secret','sephora','ulta','shopify','overstock','newegg','b&h photo','adorama','buy.com','rakuten','groupon','living social','wish ','temu ','shein '] },
  'Entertainment': { color:'#ec4899', icon:'🎬', kw:['netflix','spotify','hulu','disney+','disney plus','hbo','peacock','paramount','apple tv','youtube premium','twitch','movie theater','amc theaters','regal cinema','cinemark','concert','ticketmaster','stubhub','eventbrite','steam ','playstation','xbox live','nintendo','gamestop','bowling','miniature golf','escape room','laser tag','topgolf','golf ','paintball','museum','zoo ','aquarium','six flags','universal studios','disneyland','disney world','sea world','busch gardens','cedar point'] },
  'Healthcare':    { color:'#14b8a6', icon:'💊', kw:['pharmacy','hospital','doctor','medical','dental','dentist','orthodontist','vision care','optometrist','cvs pharmacy','walgreens pharmacy','rite aid','health clinic','urgent care','emergency room','laboratory','radiology','therapy','psychiatry','mental health','chiropractor','physical therapy','surgery','prescription','medication','vitamins','supplement','quest diagnostics','labcorp','medline','ameritas','delta dental','eye care','kaiser','aetna claim','anthem claim'] },
  'Utilities':     { color:'#f59e0b', icon:'💡', kw:['electric','electricity','water bill','internet','comcast','xfinity','spectrum','cox comm','at&t ','verizon ','t-mobile','sprint ','phone bill','mobile plan','cable tv','utility','pg&e','con edison','duke energy','dominion energy','sewer','garbage','waste mgmt','natural gas','peco','eversource','pseg','google fi','national grid','centerpoint','sce ','sdge','southern california gas','columbia gas','nicor','peoples gas','questar gas','laclede gas'] },
  'Housing':       { color:'#78716c', icon:'🏠', kw:['rent ','mortgage','hoa fee','homeowner','property tax','zillow','realtor','real estate','apartment','lease payment','maintenance','plumber','electrician','cleaning service','lawn','pest control','locksmith','home depot service','lowes service','painting','flooring','roofing','hvac','appliance','furniture','mattress firm','ashley furniture','rooms to go','ikea furniture','west elm','crate and barrel','pottery barn','restoration hardware','home goods','homegoods'] },
  'Travel':        { color:'#0ea5e9', icon:'✈️', kw:['hotel','airbnb','expedia','booking.com','marriott','hilton','hyatt','holiday inn','sheraton','wyndham','vacation','resort','delta air','united airlines','american airlines','southwest air','jetblue','spirit airlines','frontier air','alaska air','kayak','priceline','trivago','cruise','carnival cruise','royal caribbean','norwegian cruise','travel insurance','global entry','tsa precheck','currency exchange','foreign transaction'] },
  'Insurance':     { color:'#6366f1', icon:'🛡️', kw:['insurance','geico','progressive','allstate','state farm','nationwide','farmers ins','liberty mutual','usaa','esurance','travelers ins','aetna','cigna','humana','blue cross','blue shield','metlife','prudential','aflac','unum','guardian life','auto insurance','renters insurance','life insurance','health insurance','dental insurance','vision insurance','homeowner insurance'] },
  'Education':     { color:'#84cc16', icon:'📚', kw:['tuition','university','college','udemy','coursera','linkedin learning','masterclass','pluralsight','skillshare','textbook','student loan','student aid','tutoring','school fee','khan academy','duolingo','chegg','course hero','campus','bookstore','educational','pearson','mcgraw hill','cengage','academic','study.com','wyzant','varsity tutors'] },
  'Personal Care': { color:'#fb923c', icon:'💅', kw:['salon','haircut','barber','spa ','massage','nail salon','beauty supply','gym ','fitness','planet fitness','la fitness','anytime fitness','orange theory','peloton','crossfit','yoga studio','pilates','personal trainer','grooming','dry clean','laundromat','supercuts','great clips','sport clips','hair cuttery','fantastic sams','regis salon'] },
  'Subscriptions': { color:'#c084fc', icon:'📱', kw:['subscription','membership','annual fee','monthly fee','adobe ','microsoft 365','office 365','dropbox','icloud','google one','amazon prime','costco membership','sam\'s club membership','aaa membership','instacart express','doordash dashpass','grubhub+','nytimes','wsj ','washington post','the atlantic','medium ','substack','patreon','onlyfans','crunchyroll','funimation','paramount+','apple one','apple arcade','apple music','tidal ','deezer','pandora premium'] },
  'Transfer':      { color:'#94a3b8', icon:'↔️', kw:['transfer','atm ','withdrawal','zelle ','venmo','paypal','cash app','wire transfer','ach ','western union','moneygram','remittance','chase quickpay','apple pay cash','google pay send'] },
  'Other':         { color:'#6b7280', icon:'📋', kw:[] },
};

const ALL_CATS = Object.keys(CAT);

function categorize(desc) {
  const low = desc.toLowerCase();
  for (const [cat, cfg] of Object.entries(CAT)) {
    if (cat === 'Other') continue;
    for (const kw of cfg.kw) {
      if (low.includes(kw)) return cat;
    }
  }
  return 'Other';
}
